%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:/Users/16084/Documents/MATLAB/good.csv
%
% Auto-generated by MATLAB on 25-Sep-2023 20:42:24

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Site", "Year", "potato_intensity", "Lon", "Lat", "CPBA", "CPBL", "Month", "tavg", "tmin", "tmax", "category", "Prop_potato", "Day_in_Month"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "category", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:/Users/16084/Documents/MATLAB/good.csv", opts);

%% Convert to output type
%{
VarName1 = tbl.VarName1;
Site = tbl.Site;
Year = tbl.Year;
Lon = tbl.Lon;
Lat = tbl.Lat;
Month = tbl.Month;
tavg = tbl.tavg;
tmin = tbl.tmin;
tmax = tbl.tmax;
category = tbl.category;
Prop_potato = tbl.Prop_potato;
Day_in_Month = tbl.Day_in_Month;
%}
potato_intensity = tbl.potato_intensity;
CPBA = tbl.CPBA;
CPBL = tbl.CPBL;

%% Clear temporary variables
clear opts tbl

%% 
a = linspace(0,1,20); %20可以变大，密集一些，多看看plot
b = 1-a;
mkdir myfolder

for i = 1:length(a)
    abundance = a(i) * CPBA + b(i) * CPBL;
    weight_vector = sqrt((potato_intensity-mean(potato_intensity)).^2);

    abundance_gap = 0:0.5:max(abundance); %0.5可以变，变大就gap覆盖的点多
    potato_intensity_mean = zeros(size(abundance_gap));

    for j = 1:length(abundance_gap)-1
        index = ( (abundance>=abundance_gap(j))&(abundance<=abundance_gap(j+1)) );
        potato_intensity_selected = potato_intensity(index).*weight_vector(index);
        potato_intensity_mean(j) = mean(potato_intensity_selected);
    end
    figure('Visible','off');
    filename = strcat('./myfolder/the ',num2str(i),'plot.png');
    h = plot(abundance_gap,potato_intensity_mean);
    xlabel('abundance gap')
    ylabel('potato intensity mean at each gap')
    saveas(gcf,filename)
end
%% 
[fitresult, gof] = createFit1(abundance_gap(1:48), potato_intensity_mean(1:48)); %最后这行1:48看着选；能做出来exp decay就行

%%
function [fitresult, gof] = createFit1(x, y)
% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.131973292606335 0.942050590775485 0.956134540229802];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'abundance v. potato plot', 'curve fitting' );
figure('Visible','on')
h = plot( fitresult, xData, yData );
legend( h, 'abundance v. potato intensity', 'exp decay fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'abundance', 'Interpreter', 'none' );
ylabel( 'potato intensity', 'Interpreter', 'none' );
grid on
end

